### PR TITLE
[Enhancement] Adding features and bugs resolved (#120) , (#119), (#118), (#117), (#116)

### PR DESCRIPTION
**Pull request by kapilip**
# Description
Fixed issues
1. User can open now edit profile section from header.
2. Fixed the banner image at image editor shows.
3.  Enhancement: Uploading profile Image in background.
4. Fixed the comments issue.
5. Feeds and album for the user are displayed now.

💔Thank you!

### CODE REVIEW

**Comment by Qolzam** [comment]
Relate to (#120) , (#119), (#118), (#117), (#116)

**Comment by Qolzam** [comment]
@kapilip , @Abhiranjanchaurasia I really appreciate the pull request.

**Comment by Qolzam** [comment]
@kapilip can you ping me in gitter or email to talk about the plan?

**Comment by ipragmatechadmin** [comment]
@Qolzam It's our pleasure to work on this project and looking forward to add value to this project. Sure, We can discuss the plan on gitter. I have sent a message in gitter.

**Pull request merged**
